"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { use, useCallback, useEffect, useMemo, useState } from "react";
import { AccessDenied } from "../../../components/access-denied";
import { AssertionsPanel } from "../../../components/assertions-panel";
import { useAuth } from "../../../components/auth-context";
import { CompletenessPanel } from "../../../components/completeness-panel";
import { DependencyAnalysisPanel } from "../../../components/dependency-analysis-panel";
import { PageHeader } from "../../../components/page-header";
import { OperationalGraphView } from "../../../components/operational-graph-view";
import { StatusBadge } from "../../../components/status-badge";
import { TimelineEvent } from "../../../components/timeline-event";
import { recordContextOptions } from "../../../lib/record-context.mjs";
import { apiRequest } from "../../../lib/api";
import { DEPENDENCY_REQUIREMENT_LABELS, DEPENDENCY_STRATEGY_LABELS, FAILURE_EFFECT_LABELS, dependencySemanticsLabels } from "../../../lib/dependency-semantics.mjs";
import { formatDuration } from "../../../lib/duration.mjs";

function DependencySemantics({ dependency, canManage, onRequirement }) {
  const labels = dependencySemanticsLabels(dependency);
  return <div className="dependency-semantics" aria-label="Dependency semantics">
    {canManage && !dependency.dependency_group_id
      ? <label><span className="sr-only">Requirement</span><select aria-label="Requirement" disabled={false} value={dependency.dependency_requirement || (dependency.required_for_operation ? "required" : "optional")} onChange={(event) => onRequirement(event.target.value)}><option value="required">Required</option><option value="optional">Optional</option></select></label>
      : <span>{labels.requirement}</span>}
    {labels.strategy && <span>{labels.strategy}</span>}
    <span>If unavailable: {labels.failureEffect}</span>
    {dependency.dependency_group_name && <small>Dependency behaviour: {dependency.dependency_group_name}</small>}
  </div>;
}

export default function ServiceDetailPage({ params }) {
  const { id } = use(params); const router = useRouter(); const searchParams = useSearchParams(); const { hasPermission, hasPermissionForObject } = useAuth();
  const [service, setService] = useState(null); const [assetDependencies, setAssetDependencies] = useState([]); const [serviceDependencies, setServiceDependencies] = useState([]); const [dependencyGroups, setDependencyGroups] = useState([]); const [functionLinks, setFunctionLinks] = useState([]); const [completeness, setCompleteness] = useState(null); const [changes, setChanges] = useState([]); const [assertions, setAssertions] = useState([]); const [graph, setGraph] = useState({ nodes: [], edges: [] });
  const [assets, setAssets] = useState([]); const [services, setServices] = useState([]); const [functions, setFunctions] = useState([]); const [assetRelations, setAssetRelations] = useState([]); const [serviceRelations, setServiceRelations] = useState([]); const [businessRelations, setBusinessRelations] = useState([]);
  const [assetForm, setAssetForm] = useState({ asset_id: "", relationship_type_id: "", required_for_operation: true, description: "" }); const [serviceForm, setServiceForm] = useState({ target_service_id: "", relationship_type_id: "", required_for_operation: true, description: "" }); const [functionForm, setFunctionForm] = useState({ business_function_id: "", relationship_type_id: "", is_primary: false, importance: "", description: "" });
  const [groupForm, setGroupForm] = useState({ name: "", strategy: "all", requirement: "required", failure_effect: "unknown", asset_dependency_ids: [], service_dependency_ids: [] });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const canView = hasPermission("services.view");
  const load = useCallback(async () => {
    if (!canView) return; setLoading(true); setError("");
    try {
      const item = await apiRequest(`/services/${id}`); setService(item);
      const recordContext = recordContextOptions(item.customer_id, item.site_id);
      const canDependencies = hasPermissionForObject("service_dependencies.view", item.customer_id, item.site_id);
      const canFunctions = hasPermissionForObject("business_functions.view", item.customer_id, item.site_id);
      const [assetDeps, serviceDeps, groups, links, complete, history, sourceAssertions, graphData, assetRows, serviceRows, functionRows, assetRelRows, serviceRelRows, businessRelRows] = await Promise.all([
        canDependencies ? apiRequest(`/services/${id}/asset-dependencies`) : [], canDependencies ? apiRequest(`/services/${id}/service-dependencies`) : [], canDependencies ? apiRequest(`/services/${id}/dependency-groups`) : [], canFunctions ? apiRequest(`/services/${id}/business-functions`) : [],
        hasPermission("knowledge_gaps.view") ? apiRequest(`/services/${id}/completeness`) : null, hasPermission("changes.view") ? apiRequest(`/services/${id}/history`) : [], apiRequest(`/services/${id}/assertions?current_only=false`), canDependencies ? apiRequest(`/services/${id}/graph`) : { nodes: [], edges: [] },
        hasPermission("service_dependencies.manage") ? apiRequest("/assets?limit=500", recordContext) : [], hasPermission("service_dependencies.manage") ? apiRequest("/services?limit=500", recordContext) : [], hasPermission("business_functions.manage") ? apiRequest("/business-functions?limit=500", recordContext) : [],
        hasPermission("service_dependencies.manage") ? apiRequest("/relationship-types?active_only=true&source_entity_type=service&target_entity_type=asset") : [], hasPermission("service_dependencies.manage") ? apiRequest("/relationship-types?active_only=true&source_entity_type=service&target_entity_type=service") : [], hasPermission("business_functions.manage") ? apiRequest("/relationship-types?active_only=true&source_entity_type=service&target_entity_type=business_function") : [],
      ]);
      setAssetDependencies(assetDeps); setServiceDependencies(serviceDeps); setDependencyGroups(groups); setFunctionLinks(links); setCompleteness(complete); setChanges(history); setAssertions(sourceAssertions); setGraph(graphData); setAssets(assetRows); setServices(serviceRows.filter((row) => row.id !== id)); setFunctions(functionRows); setAssetRelations(assetRelRows); setServiceRelations(serviceRelRows); setBusinessRelations(businessRelRows);
    } catch (requestError) { setError(requestError.message || "Atlas could not load this Service."); }
    finally { setLoading(false); }
  }, [canView, hasPermission, hasPermissionForObject, id]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (searchParams.get("created") !== "true") return; const required = Number(searchParams.get("required_gaps") || 0); const recommended = Number(searchParams.get("recommended_gaps") || 0); setSuccess(`Service created. Atlas found ${required} required gap${required === 1 ? "" : "s"} and ${recommended} recommended improvement${recommended === 1 ? "" : "s"}.`); router.replace(`/services/${id}`, { scroll: false }); }, [id, router, searchParams]);
  const assetsById = useMemo(() => Object.fromEntries(assets.map((item) => [item.id, item])), [assets]);
  if (!canView) return <AccessDenied />;
  if (loading && !service) return <div className="status-banner">Loading Service…</div>;
  if (!service) return <div className="error-banner">{error || "Service not found."}</div>;
  const canEdit = hasPermissionForObject("services.edit", service.customer_id, service.site_id); const canArchive = hasPermissionForObject("services.archive", service.customer_id, service.site_id); const canManageDependencies = hasPermissionForObject("service_dependencies.manage", service.customer_id, service.site_id); const canManageFunctions = hasPermissionForObject("business_functions.manage", service.customer_id, service.site_id);
  async function mutate(key, path, body, method = "POST") { if (method === "DELETE" && !window.confirm("Remove this link? Atlas will preserve it in dependency history.")) return false; setSaving(key); setError(""); setSuccess(""); try { await apiRequest(path, { method, ...(body ? { body: JSON.stringify(body) } : {}) }); setSuccess("Service knowledge updated."); await load(); return true; } catch (requestError) { setError(requestError.message); return false; } finally { setSaving(""); } }
  async function addAsset(event) { event.preventDefault(); if (await mutate("asset", `/services/${id}/asset-dependencies`, { ...assetForm, description: assetForm.description || null })) setAssetForm({ asset_id: "", relationship_type_id: "", required_for_operation: true, description: "" }); }
  async function addService(event) { event.preventDefault(); if (await mutate("service", `/services/${id}/service-dependencies`, { ...serviceForm, description: serviceForm.description || null })) setServiceForm({ target_service_id: "", relationship_type_id: "", required_for_operation: true, description: "" }); }
  async function addFunction(event) { event.preventDefault(); if (await mutate("function", `/services/${id}/business-functions`, { ...functionForm, relationship_type_id: functionForm.relationship_type_id || null, importance: functionForm.importance || null, description: functionForm.description || null })) setFunctionForm({ business_function_id: "", relationship_type_id: "", is_primary: false, importance: "", description: "" }); }
  async function addDependencyGroup(event) { event.preventDefault(); if (await mutate("dependency-group", `/services/${id}/dependency-groups`, groupForm)) setGroupForm({ name: "", strategy: "all", requirement: "required", failure_effect: "unknown", asset_dependency_ids: [], service_dependency_ids: [] }); }
  function toggleGroupMember(kind, dependencyId) { const key = kind === "asset" ? "asset_dependency_ids" : "service_dependency_ids"; setGroupForm((current) => ({ ...current, [key]: current[key].includes(dependencyId) ? current[key].filter((idValue) => idValue !== dependencyId) : [...current[key], dependencyId] })); }
  async function updateDependencyRequirement(dependency, kind, requirement) { const path = kind === "asset" ? `/service-asset-dependencies/${dependency.id}` : `/service-dependencies/${dependency.id}`; await mutate(`requirement-${dependency.id}`, path, { required_for_operation: requirement === "required" }, "PATCH"); }
  const outgoingServiceDependencies = serviceDependencies.filter((dependency) => dependency.source_service_id === id);
  const ungroupedAssetDependencies = assetDependencies.filter((dependency) => !dependency.dependency_group_id);
  const ungroupedServiceDependencies = outgoingServiceDependencies.filter((dependency) => !dependency.dependency_group_id);
  const dependencyNamesById = Object.fromEntries([...assetDependencies.map((dependency) => [dependency.id, dependency.asset_name || "Unavailable Asset"]), ...outgoingServiceDependencies.map((dependency) => [dependency.id, dependency.target_service_name || "Unavailable Service"])]);
  return <>
    <div className="page-heading-row"><PageHeader eyebrow="Service" title={service.name} description={service.purpose || "Purpose has not been documented."} /><div className="row-actions">{canEdit && <Link className="button button-secondary" href={`/services/${id}/edit`}>Edit Service</Link>}{canArchive && <button className="button button-secondary" onClick={() => { if (service.archived_at || window.confirm("Archive this Service? Dependencies and knowledge history will be preserved.")) mutate("archive", `/services/${id}/${service.archived_at ? "restore" : "archive"}`, service.archived_at ? null : { reason: "Archived from Service detail" }); }} type="button">{service.archived_at ? "Restore" : "Archive"}</button>}</div></div>
    {error && <div className="error-banner" role="alert">{error}</div>}{success && <div className="success-banner">{success}</div>}
    <section className="detail-card"><div className="form-card-header"><div><p className="eyebrow">Overview</p><h2>Operational identity</h2></div><div className="row-actions"><StatusBadge status={service.service_type_name || "Unavailable"} /><StatusBadge status={service.criticality_name || "Unavailable"} /><StatusBadge status={service.lifecycle_status} /><StatusBadge status={service.operational_status} /></div></div><div className="detail-grid"><div><span>Owner</span><strong>{service.owner_name || "—"}</strong></div><div><span>Technical contact</span><strong>{service.technical_contact || "—"}</strong></div><div><span>Support group</span><strong>{service.support_group || "—"}</strong></div><div><span>RTO</span><strong>{formatDuration(service.rto_minutes)}</strong><small>Suggested: {formatDuration(service.suggested_rto_minutes)}</small></div><div><span>RPO</span><strong>{formatDuration(service.rpo_minutes)}</strong><small>Suggested: {formatDuration(service.suggested_rpo_minutes)}</small></div><div><span>Scope</span><strong>{service.site_id ? "Site" : "Customer-wide"}</strong></div></div>{service.description && <p>{service.description}</p>}<div className="row-actions">{service.runbook_url && <a className="card-link" href={service.runbook_url} target="_blank" rel="noreferrer">Open runbook ↗</a>}{service.documentation_url && <a className="card-link" href={service.documentation_url} target="_blank" rel="noreferrer">Open documentation ↗</a>}</div></section>
    {hasPermission("knowledge_gaps.view") && <CompletenessPanel canDefer={hasPermissionForObject("knowledge_gaps.defer", service.customer_id, service.site_id)} canEvaluate={hasPermissionForObject("service_completeness.evaluate", service.customer_id, service.site_id)} canExcept={hasPermissionForObject("knowledge_gaps.exception", service.customer_id, service.site_id)} completeness={completeness} entityType="service" onChanged={load} serviceId={id} />}
    {hasPermission("service_dependencies.view") && <section className="detail-card">
      <div className="form-card-header"><div><p className="eyebrow">Infrastructure</p><h2>Asset dependencies</h2></div><span>{assetDependencies.length} active</span></div>
      {assetDependencies.length === 0 && <p className="empty-state">No Asset dependencies yet.</p>}
      <div className="dependency-list">{assetDependencies.map((dependency) => <article className="dependency-row" key={dependency.id}><div><Link href={`/assets/${dependency.asset_id}`}><strong>{dependency.asset_name || "Unavailable Asset"}</strong></Link><span>{dependency.relationship_type_name || dependency.source_label || "Depends on"} · {dependency.asset_type || "Unknown type"}</span>{dependency.description && <small>{dependency.description}</small>}<DependencySemantics dependency={dependency} canManage={canManageDependencies} onRequirement={(requirement) => updateDependencyRequirement(dependency, "asset", requirement)} /></div>{canManageDependencies && <button className="text-button text-danger" onClick={() => mutate(dependency.id, `/service-asset-dependencies/${dependency.id}`, null, "DELETE")} type="button">Remove</button>}</article>)}</div>
      {canManageDependencies && <form className="inline-dependency-form" onSubmit={addAsset}><select required value={assetForm.asset_id} onChange={(event) => setAssetForm({ ...assetForm, asset_id: event.target.value })}><option value="">Choose Asset</option>{assets.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.asset_type}</option>)}</select><select required value={assetForm.relationship_type_id} onChange={(event) => setAssetForm({ ...assetForm, relationship_type_id: event.target.value })}><option value="">Relationship</option>{assetRelations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input placeholder="Description (optional)" value={assetForm.description} onChange={(event) => setAssetForm({ ...assetForm, description: event.target.value })} /><label className="checkbox-field"><input checked={assetForm.required_for_operation} type="checkbox" onChange={(event) => setAssetForm({ ...assetForm, required_for_operation: event.target.checked })} /><span>Required</span></label><button className="button button-secondary" disabled={saving === "asset"} type="submit">Add Asset</button></form>}
    </section>}
    {hasPermission("service_dependencies.view") && <section className="detail-card">
      <div className="form-card-header"><div><p className="eyebrow">Dependencies</p><h2>Services</h2></div><span>{serviceDependencies.length} connected</span></div>
      {serviceDependencies.length === 0 && <p className="empty-state">No Service dependencies yet.</p>}
      <div className="dependency-list">{serviceDependencies.map((dependency) => { const outgoing = dependency.source_service_id === id; const otherId = outgoing ? dependency.target_service_id : dependency.source_service_id; const otherName = outgoing ? dependency.target_service_name : dependency.source_service_name; return <article className="dependency-row" key={dependency.id}><div><span>{outgoing ? "Depends on" : "Required by"}</span><Link href={`/services/${otherId}`}><strong>{otherName || "Unavailable Service"}</strong></Link><small>{dependency.relationship_type_name || "Dependency"}</small>{outgoing && <DependencySemantics dependency={dependency} canManage={canManageDependencies} onRequirement={(requirement) => updateDependencyRequirement(dependency, "service", requirement)} />}</div>{canManageDependencies && outgoing && <button className="text-button text-danger" onClick={() => mutate(dependency.id, `/service-dependencies/${dependency.id}`, null, "DELETE")} type="button">Remove</button>}</article>; })}</div>
      {canManageDependencies && <form className="inline-dependency-form" onSubmit={addService}><select required value={serviceForm.target_service_id} onChange={(event) => setServiceForm({ ...serviceForm, target_service_id: event.target.value })}><option value="">Choose Service</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required value={serviceForm.relationship_type_id} onChange={(event) => setServiceForm({ ...serviceForm, relationship_type_id: event.target.value })}><option value="">Relationship</option>{serviceRelations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input placeholder="Description (optional)" value={serviceForm.description} onChange={(event) => setServiceForm({ ...serviceForm, description: event.target.value })} /><label className="checkbox-field"><input checked={serviceForm.required_for_operation} type="checkbox" onChange={(event) => setServiceForm({ ...serviceForm, required_for_operation: event.target.checked })} /><span>Required</span></label><button className="button button-secondary" disabled={saving === "service"} type="submit">Add Service</button></form>}
    </section>}
    {hasPermission("service_dependencies.view") && <section className="detail-card">
      <div className="form-card-header"><div><p className="eyebrow">Dependency semantics</p><h2>Dependency behaviour</h2></div><span>{dependencyGroups.length} {dependencyGroups.length === 1 ? "set" : "sets"}</span></div>
      <p className="secondary-text">Group dependencies that satisfy the same operational need, then describe whether all or any one is sufficient.</p>
      {dependencyGroups.length === 0 && <p className="empty-state">No grouped dependency behaviour yet. Ungrouped dependencies keep their required or optional setting and an Unknown failure effect.</p>}
      <div className="dependency-list">{dependencyGroups.map((group) => <article className="dependency-row dependency-group-row" key={group.id}><div><strong>{group.name}</strong><span>{DEPENDENCY_REQUIREMENT_LABELS[group.requirement]} · {DEPENDENCY_STRATEGY_LABELS[group.strategy]}</span><small>If unavailable: {FAILURE_EFFECT_LABELS[group.failure_effect]}</small><small>{[...group.asset_dependency_ids, ...group.service_dependency_ids].map((memberId) => dependencyNamesById[memberId] || "Unavailable dependency").join(" · ")}</small></div>{canManageDependencies && <div className="dependency-group-actions"><label><span>Behaviour</span><select aria-label={`${group.name} behaviour`} value={group.strategy} onChange={(event) => mutate(`group-${group.id}`, `/dependency-groups/${group.id}`, { strategy: event.target.value }, "PATCH")}><option value="all">All required</option><option value="any">Any one is sufficient</option></select></label><label><span>Required</span><select aria-label={`${group.name} requirement`} value={group.requirement} onChange={(event) => mutate(`group-${group.id}`, `/dependency-groups/${group.id}`, { requirement: event.target.value }, "PATCH")}><option value="required">Required</option><option value="optional">Optional</option></select></label><label><span>If unavailable</span><select aria-label={`${group.name} failure effect`} value={group.failure_effect} onChange={(event) => mutate(`group-${group.id}`, `/dependency-groups/${group.id}`, { failure_effect: event.target.value }, "PATCH")}><option value="unavailable">Service unavailable</option><option value="degraded">Service degraded</option><option value="unknown">Unknown</option></select></label><button className="text-button text-danger" onClick={() => mutate(group.id, `/dependency-groups/${group.id}`, null, "DELETE")} type="button">Remove behaviour</button></div>}</article>)}</div>
      {canManageDependencies && (ungroupedAssetDependencies.length > 0 || ungroupedServiceDependencies.length > 0) && <form className="dependency-group-form" onSubmit={addDependencyGroup}><div className="form-grid"><label><span>Name</span><input required maxLength={255} placeholder="e.g. DNS providers" value={groupForm.name} onChange={(event) => setGroupForm({ ...groupForm, name: event.target.value })} /></label><label><span>Dependency behaviour</span><select value={groupForm.strategy} onChange={(event) => setGroupForm({ ...groupForm, strategy: event.target.value })}><option value="all">All required</option><option value="any">Any one is sufficient</option></select></label><label><span>Requirement</span><select value={groupForm.requirement} onChange={(event) => setGroupForm({ ...groupForm, requirement: event.target.value })}><option value="required">Required</option><option value="optional">Optional</option></select></label><label><span>If unavailable</span><select value={groupForm.failure_effect} onChange={(event) => setGroupForm({ ...groupForm, failure_effect: event.target.value })}><option value="unavailable">Service unavailable</option><option value="degraded">Service degraded</option><option value="unknown">Unknown</option></select></label></div><fieldset><legend>Dependencies in this set</legend><div className="dependency-member-options">{ungroupedAssetDependencies.map((dependency) => <label className="checkbox-field" key={dependency.id}><input checked={groupForm.asset_dependency_ids.includes(dependency.id)} type="checkbox" onChange={() => toggleGroupMember("asset", dependency.id)} /><span>{dependency.asset_name || "Unavailable Asset"}</span></label>)}{ungroupedServiceDependencies.map((dependency) => <label className="checkbox-field" key={dependency.id}><input checked={groupForm.service_dependency_ids.includes(dependency.id)} type="checkbox" onChange={() => toggleGroupMember("service", dependency.id)} /><span>{dependency.target_service_name || "Unavailable Service"}</span></label>)}</div></fieldset><button className="button button-secondary" disabled={saving === "dependency-group" || (groupForm.asset_dependency_ids.length + groupForm.service_dependency_ids.length === 0)} type="submit">Add dependency behaviour</button></form>}
    </section>}
    {hasPermission("business_functions.view") && <section className="detail-card"><div className="form-card-header"><div><p className="eyebrow">Purpose</p><h2>Business Functions</h2></div><Link className="card-link" href="/business-functions">Browse functions →</Link></div>{functionLinks.length === 0 && <p className="empty-state">No Business Functions linked yet.</p>}<div className="dependency-list">{functionLinks.map((link) => <article className="dependency-row" key={link.id}><div><Link href={`/business-functions/${link.business_function_id}`}><strong>{link.business_function_name || "Unavailable Function"}</strong></Link><span>{link.relationship_label}{link.is_primary ? " · Primary" : ""}</span></div>{canManageFunctions && <button className="text-button text-danger" onClick={() => mutate(link.id, `/service-business-functions/${link.id}`, null, "DELETE")} type="button">Remove</button>}</article>)}</div>{canManageFunctions && <form className="inline-dependency-form" onSubmit={addFunction}><select required value={functionForm.business_function_id} onChange={(event) => setFunctionForm({ ...functionForm, business_function_id: event.target.value })}><option value="">Choose Business Function</option>{functions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={functionForm.relationship_type_id} onChange={(event) => setFunctionForm({ ...functionForm, relationship_type_id: event.target.value })}><option value="">Supports (default)</option>{businessRelations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label className="checkbox-field"><input checked={functionForm.is_primary} type="checkbox" onChange={(event) => setFunctionForm({ ...functionForm, is_primary: event.target.checked })} /><span>Primary</span></label><button className="button button-secondary" disabled={saving === "function"} type="submit">Link Function</button></form>}</section>}
    {!service.archived_at && hasPermissionForObject("service_dependencies.view", service.customer_id, service.site_id) && <DependencyAnalysisPanel focusType="service" focusId={id} />}
    {graph.nodes.length > 0 && <section className="detail-card"><div className="form-card-header"><div><p className="eyebrow">Projection</p><h2>Service graph</h2></div></div><OperationalGraphView graph={graph} /></section>}
    <section className="detail-card"><div className="form-card-header"><div><p className="eyebrow">Recovery</p><h2>Recovery knowledge</h2></div></div><div className="prose-content"><h3>Recovery notes</h3><p>{service.recovery_notes || "Not documented."}</p><h3>Backup notes</h3><p>{service.backup_notes || "Not documented."}</p><h3>General notes</h3><p>{service.notes || "—"}</p></div></section>
    {hasPermission("changes.view") && <section className="detail-card"><div className="form-card-header"><div><p className="eyebrow">History</p><h2>Meaningful changes</h2></div></div>{changes.length === 0 ? <p className="empty-state">No Service history yet.</p> : <div className="timeline">{changes.map((change) => <TimelineEvent key={change.id}><div className="timeline-heading"><strong>{change.summary}</strong><time>{new Date(change.occurred_at).toLocaleString()}</time></div>{change.predicate && <small>{change.predicate.replaceAll("_", " ")}</small>}</TimelineEvent>)}</div>}</section>}
    <AssertionsPanel assertions={assertions} assetsById={assetsById} canDelete={hasPermission("assertions.delete")} canRetract={hasPermission("assertions.retract")} entityLabel="Service" onChanged={load} />
  </>;
}
