import json
import re
import uuid
from dataclasses import dataclass
from datetime import datetime

from atlas_plugin_sdk import (
    NormalizedAsset,
    NormalizedRelationship,
)

MARKDOWN_SPECIAL = re.compile(r"([\\`*{}\[\]()#+.!|_>-])")


@dataclass(frozen=True, slots=True)
class GeneratedMarkdownDocument:
    title: str
    content_markdown: str


def escape_markdown(value: object) -> str:
    """Render untrusted normalized values as single-line Markdown text."""

    single_line = " ".join(str(value).splitlines())
    single_line = single_line.replace("<", "&lt;").replace(">", "&gt;")
    return MARKDOWN_SPECIAL.sub(r"\\\1", single_line)


def format_value(value: object) -> str:
    if isinstance(value, (dict, list, tuple)):
        value = json.dumps(value, ensure_ascii=False, sort_keys=True)
    elif isinstance(value, bool):
        value = "Yes" if value else "No"
    elif value is None:
        value = "—"
    return escape_markdown(value)


def humanize(value: str) -> str:
    return value.replace("_", " ").strip().title()


def generate_asset_document(
    asset: NormalizedAsset,
    assets_by_external_id: dict[str, NormalizedAsset],
    relationships: tuple[NormalizedRelationship, ...],
    *,
    discovery_run_id: uuid.UUID,
    observed_at: datetime,
) -> GeneratedMarkdownDocument:
    """Generate a deterministic page from normalized data only."""

    safe_name = escape_markdown(asset.name)
    title_name = " ".join(asset.name.splitlines()).strip()[:220] or asset.external_id[:220]
    lines = [
        f"# {safe_name}",
        "",
        "## Overview",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Asset type | {format_value(humanize(asset.asset_type))} |",
        f"| Vendor | {format_value(asset.vendor)} |",
        f"| Status | {format_value(humanize(asset.status))} |",
        f"| External ID | `{escape_markdown(asset.external_id)}` |",
        f"| Last observed | {format_value(observed_at.isoformat())} |",
    ]

    if asset.description:
        lines.extend(["", "## Description", "", escape_markdown(asset.description)])

    lines.extend(["", "## Metadata", ""])
    if asset.metadata:
        lines.extend(["| Key | Value |", "| --- | --- |"])
        for key, value in sorted(asset.metadata.items()):
            lines.append(f"| {escape_markdown(key)} | {format_value(value)} |")
    else:
        lines.append("No metadata was reported.")

    lines.extend(["", "## Facts", ""])
    if asset.facts:
        lines.extend(["| Fact | Value | Source |", "| --- | --- | --- |"])
        for fact in sorted(asset.facts, key=lambda item: (item.key, item.source)):
            lines.append(
                f"| {escape_markdown(fact.key)} | {format_value(fact.value)} | "
                f"{escape_markdown(fact.source)} |"
            )
    else:
        lines.append("No facts were reported.")

    relevant = [
        relationship
        for relationship in relationships
        if asset.external_id
        in {
            relationship.source_external_id,
            relationship.target_external_id,
        }
    ]
    relevant.sort(
        key=lambda item: (
            item.relationship_type,
            item.source_external_id,
            item.target_external_id,
        )
    )
    lines.extend(["", "## Relationships", ""])
    if relevant:
        lines.extend(
            ["| Direction | Relationship | Related asset |", "| --- | --- | --- |"]
        )
        for relationship in relevant:
            outgoing = relationship.source_external_id == asset.external_id
            related_id = (
                relationship.target_external_id
                if outgoing
                else relationship.source_external_id
            )
            related = assets_by_external_id.get(related_id)
            related_name = related.name if related is not None else related_id
            lines.append(
                f"| {'Outgoing' if outgoing else 'Incoming'} | "
                f"{format_value(humanize(relationship.relationship_type))} | "
                f"{escape_markdown(related_name)} (`{escape_markdown(related_id)}`) |"
            )
    else:
        lines.append("No relationships were reported.")

    lines.extend(
        [
            "",
            "---",
            "",
            f"Generated by Atlas from discovery run `{discovery_run_id}`.",
            "",
        ]
    )
    return GeneratedMarkdownDocument(
        title=f"{title_name} — Asset Documentation",
        content_markdown="\n".join(lines),
    )
